name: Release

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Create env file
        uses: 1arp/create-a-file-action@0.2
        with:
          file: .env
          content: |
            POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        run: docker-compose -f docker-compose.production.yaml build
      - name: Push
        run: docker-compose -f docker-compose.production.yaml push

      - name: Deploy to VPS
        uses: 5eqn/docker-compose-remote-action@master
        with:
          docker_compose_filename: docker-compose.production.yaml
          ssh_host: 83.147.246.7
          ssh_user: root
          docker_args: -d --force-recreate --env-file ./.env
          docker_compose_prefix: kusochek
          ssh_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          ssh_host_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}