name: Release

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Create env file
        uses: 1arp/create-a-file-action@0.2
        with:
          file: .env
          content: |
            POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            VK_SERVICE_TOKEN=${{ secrets.VK_SERVICE_TOKEN }}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: makeitokay
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        run: docker-compose -f docker-compose.production.yaml build
      - name: Push
        run: docker-compose -f docker-compose.production.yaml push

      - name: Deploy to VPS
        uses: makeitokay/docker-remote-deployment-action@master
        with:
          stack_file_name: docker-compose.production.yaml
          remote_docker_host: root@83.147.246.7
          ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
          args: --env-file ./.env up -d --force-recreate